### ISSUE TITLE
How to read Uri Param ,Query Parameters type

### ISSUE THREAD

**Issue by anilmanchala07** [raml-org/webapi-parser#60]
I am parsing an RML file with a new Webapi parser- 0.2.0. I have a requirement to read URI parameters and Query parameters along with name, default value and type of the parameter. I am able to get name and default values fro Parameter class but I am finding out a way to get parameter type (ex: String, Integer, Boolean Object. Can somebody help me on finding out parameter type?

**Comment by postatum** [comment]
Hi @anilmanchala07. Please note that the latest webapi-parser version is 0.4.0.

To get a type of Parameter 

```js
const typeName = getShapeType(parameter.schema)
```
where `getShapeType` is a function implemented like [this](https://github.com/mulesoft-labs/node-raml-sanitize/blob/f628263872459c20a08ed85accb49fda31dfdf78/raml-sanitize.js#L353) or [this](https://github.com/mulesoft-labs/node-raml-sanitize/blob/rework_webapi_parser/raml-sanitize.js#L366).

---

*Extra details which may not come handy if the first code example works fine.*

The second implementation of `getShapeType` does not depend on `webapi-parser` and may be used to get type in a library/environment different from the one you've parsed your RAML in. See this for a corner case example https://github.com/aml-org/amf/issues/569

**Comment by postatum** [comment]
If this doesn't help, feel free to reopen this issue.

**Comment by anilmanchala07** [comment]
@postatum  Thank you for quick response. 
Do we have  any examples in java ?
Does this implementation work for 0.2.0 version ?

**Comment by postatum** [comment]
> Do we have any examples in java ?

We have java examples [here](https://github.com/raml-org/webapi-parser/tree/master/examples/java/src/main/java/co/acme) though here's the only snippet related to your question I could find: [code](https://github.com/raml-org/webapi-parser/blob/8fc840006d9f7b103f25bc205a2c84e320bcec65/examples/java/src/main/java/co/acme/model/Raml10Navigation.java#L104).

I think translating js code I've linked in my previous comment to java should be straightforward. You just get an instance of [`AnyShape`](https://raml-org.github.io/webapi-parser/js/classes/_amf_client_js_.model.domain.anyshape.html) from [`Parameter`](https://raml-org.github.io/webapi-parser/js/classes/_amf_client_js_.model.domain.parameter.html) via [`.schema()`](https://raml-org.github.io/webapi-parser/js/classes/_amf_client_js_.model.domain.parameter.html#schema) call and then check its instance against webapi-parser classes in the order linked code does.


> Does this implementation work for 0.2.0 version ?

Yes, it should work. Though you may need to use `shape.dataType()` to get a string name of a ScalarShape instead of `shape.dataType.value()` because this API changes since [version 0.3.0](https://github.com/raml-org/webapi-parser/releases/tag/v0.3.0)

**Comment by anilmanchala07** [comment]
@postatum ,

I am not aware of javascript much. In below snippet code are we calling the getShape function recursively? Please correct me if I am wrong .  

if (shape instanceof domain.UnionShape) {
    return shape.anyOf.map(getShapeType)
  }

**Comment by postatum** [comment]
@anilmanchala07 Yes.

Here's a pseudo-code of that function logic:

```
function getShapeType (shape) {
  if shape is instance of amf.client.model.domain.ArrayShape {
    return = 'array'
  }
  if shape is instance of amf.client.model.domain.NodeShape {
    return = 'object'
  }
  if shape is instance of amf.client.model.domain.UnionShape {
    return = call getShapeType for each of its elements and get an array of strings back
  }
  if shape is instance of amf.client.model.domain.ScalarShape {
    return = split shape.dataType() by '#' char and return the last piece
  }
}
```

**Comment by anilmanchala07** [comment]
@postatum 

I really appreciate your quick responses. This helped me very much.
I thank you once again for the kind of explanation you provided.

**Comment by postatum** [comment]
You are welcome @anilmanchala07 :)

**Comment by anilmanchala07** [comment]
@postatum 
Could you please guide me in reading PathParameters of an Endpoint

**Comment by anilmanchala07** [comment]
@postatum 
Could you please guide me in reading path parameters. I tried with EndPoint.parameters().
Ex:  /products/{productId}
I want to get {productId} as a Parameter Object
